# Generated by Django 6.0 on 2025-12-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerevalAdded',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('raw_data', models.JSONField()),
                ('images', models.JSONField()),
                ('status', models.CharField(choices=[('new', 'Новый'), ('pending', 'В работе'), ('accepted', 'Принят'), ('rejected', 'Отклонен')], default='new', max_length=20)),
            ],
            options={
                'db_table': 'pereval_added',
            },
        ),
        migrations.CreateModel(
            name='PerevalAreas',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('id_parent', models.BigIntegerField()),
                ('title', models.TextField()),
            ],
            options={
                'db_table': 'pereval_areas',
            },
        ),
        migrations.CreateModel(
            name='PerevalImages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('img', models.BinaryField()),
            ],
            options={
                'db_table': 'pereval_images',
            },
        ),
        migrations.CreateModel(
            name='SprActivitiesTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
            ],
            options={
                'db_table': 'spr_activities_types',
            },
        ),
    ]
